### ISSUE TITLE
[Bug]: PositionTest

### ISSUE THREAD

**Issue by StevenC8661476** [THUASTA/EDCHost#37]
### Describe the bug

Test failed in #36 :

```
Error: /home/runner/work/EDCHost/EDCHost/src/EdcHost.Tests/UnitTests/Games/Game.PositionTests.cs(27,57): error CS8602: Dereference of a possibly null reference. [/home/runner/work/EDCHost/EDCHost/src/EdcHost.Tests/EdcHost.Tests.csproj]
Error: /home/runner/work/EDCHost/EDCHost/src/EdcHost.Tests/UnitTests/Games/Game.PositionTests.cs(27,41): error CS8600: Converting null literal or possible null value to non-nullable type. [/home/runner/work/EDCHost/EDCHost/src/EdcHost.Tests/EdcHost.Tests.csproj]
```

And in `PositionTest.cs`, there are something like:

```csharp

        MethodInfo? toIntPositionMethod = typeof(Game).GetMethod("ToIntPosition", BindingFlags.NonPublic | BindingFlags.Instance);
        ...
        IPosition<int> actualPosition = (IPosition<int>)toIntPositionMethod.Invoke(game, new object[] { fPosition });
```

in which `MethodInfo?` object may be `null`, but is dereferenced without checking.

### To Reproduce

_

### Expected behavior

Derefence an object only when it is not null
